language: node_js
node_js:
  - 7
  - 6
  #- 4
before_script:
  - sudo apt-get install -y vagrant npm
  - npm install -g yo
script:
  - npm test
  - sudo npm link /home/travis/build/danie1cohen/generator-vagrant-docker
  - mkdir demo && cd demo && yes '' | yo vagrant-docker && vagrant up
after_script: 'cat ./coverage/lcov.info | coveralls'
